---
- hosts: db
  sudo: yes

  tasks:
    - name: Ensure MySQL packages are installed.
      yum: >
        name={{ item }}
        state=installed
      with_items:
        - mysql
        - mysql-server
        - MySQL-python

    - name: Ensure MySQL is started and enabled on boot.
      service: >
        name=mysqld
        state=started
        enabled=yes

    - include: db-users-databases.yml
