---
- hosts: www
  sudo: yes

  tasks:
    - name: Install EPEL repo.
      yum: name="http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm" state=present

    - name: Import EPEL GPG key.
      rpm_key: key="/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6" state=present

    - name: Install Apache.
      yum: pkg=httpd state=installed

    - name: Ensure Apache is running and enabled at boot.
      service: name=httpd state=started enabled=yes

    - name: Install PHP.
      yum: "pkg={{ item }} state=installed enablerepo=epel"
      with_items:
        - php
        - php-mysql
        - php-pecl-memcached
      notify: restart apache

    - name: Copy our fancy server-specific home page.
      template:
        src: templates/index.php.j2
        dest: /var/www/html/index.php

  handlers:
    - name: restart apache
      service: name=httpd state=restarted
