---
- hosts: localhost
  connection: local

  tasks:
    - name: Build Docker image from Dockerfiles.
      docker_image:
        name: test
        path: test
        state: build

    - name: Ensure the test container is running.
      docker_container:
        image: test:latest
        name: test
        state: started
