---
- hosts: gluster
  sudo: yes

  vars_files:
    - vars.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.glusterfs

  tasks:
    - name: Ensure Gluster brick and mount directories exist.
      file: "path={{ item }} state=directory mode=0775"
      with_items:
        - "{{ gluster_brick_dir }}"
        - "{{ gluster_mount_dir }}"

    - name: Check if Gluster volumes already exist.
      shell: "gluster volume info"
      changed_when: false
      register: gluster_volume_info

    - name: Connect to Gluster peers.
      shell: "gluster peer probe {{ item }}"
      register: gluster_peer_probe
      changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
      failed_when: false
      with_items: groups.gluster
      when: "'Volume Name: gluster' not in gluster_volume_info.stdout"

    - name: Create Gluster volume.
      gluster_volume:
        state: present
        name: "{{ gluster_brick_name }}"
        brick: "{{ gluster_brick_dir }}"
        replicas: 2
        cluster: "{{ groups.gluster | join(',') }}"
        host: "{{ inventory_hostname }}"
        # The following two options are defaults.
        # transport: tcp
        # start_on_create: yes
        force: yes
      run_once: true

    - name: Ensure the Gluster volume is mounted.
      mount:
        name: "{{ gluster_mount_dir }}"
        src: "{{ groups.gluster[0] }}:/{{ gluster_brick_name }}"
        fstype: glusterfs
        opts: "defaults,_netdev"
        state: mounted
