---
# To run: `ansible-playbook main.yml -i inventory-local`.
- hosts: varnish
  sudo: yes
  roles:
    - geerlingguy.varnish
  tasks:
    - name: Copy Varnish configuration files.
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      notify: restart varnish
      with_items:
        - { src: templates/default.vcl, dest: /etc/varnish/default.vcl }
        - { src: templates/varnish, dest: /etc/sysconfig/varnish }

- hosts: www
  sudo: yes
  roles:
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-memcached
  tasks:
    - name: Remove the Apache test page.
      file:
        path: /var/www/html/index.html
        state: absent
    - name: Copy our fancy server-specific home page.
      template:
        src: templates/index.php.j2
        dest: /var/www/html/index.php

- hosts: db
  sudo: yes
  roles:
    - geerlingguy.mysql
  tasks:
    - name: Ensure MySQL database is present.
      mysql_db: name=mycompany_database state=present

    - name: Ensure MySQL user is present.
      mysql_user:
        name: "mycompany_user"
        host: "{{ item }}"
        password: "mysecurepassword"
        priv: "mycompany_database.*:ALL"
        state: present
      with_items:
        - 192.168.2.3
        - 192.168.2.4

- hosts: memcached
  sudo: yes
  roles:
    - geerlingguy.memcached
